src/app.py
import os
from flask import Flask
from dotenv import load_dotenv
from os.path import join, dirname
from main.blueprints import error_blueprint
from main.blueprints import home_blueprint
from main.blueprints import spotify_blueprint
from main.blueprints import setlist_blueprint

app = Flask(__name__, static_folder='static/')

load_dotenv(join(dirname(__file__), '..\.env'))

### BLUEPRINTS ###
app.register_blueprint(home_blueprint.controller)
app.register_blueprint(error_blueprint.controller)
app.register_blueprint(spotify_blueprint.controller)
app.register_blueprint(setlist_blueprint.controller)

app.secret_key = os.environ.get('APP_SECRET_KEY') 

if __name__ == '__main__':
    app.run(debug=True, use_reloader=True)

src/main/blueprints/error_blueprint.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

controller = Blueprint('error_blueprint', __name__)

@controller.app_errorhandler(404)
def show_404(e):
    return render_template('error/404_error_template.html')

@controller.app_errorhandler(500)
def show_500(e):
    return render_template('error/500_error_template.html')

src/main/blueprints/home_blueprint.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

controller = Blueprint('home_blueprint', __name__)

@controller.route('/')
def show_index():
    return render_template('home_template.html')

src/main/blueprints/setlist_blueprint.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

controller = Blueprint('setlist_blueprint', __name__)

@controller.route('/search/<query>')
def show_index(query):
    return render_template('home_template.html')

src/main/blueprints/spotify_blueprint.py
from flask import Blueprint, render_template, abort, redirect, request, session
from jinja2 import TemplateNotFound
from main.services.spotify_service import SpotifyService
from main.factories.service_factory import ServiceFactory

controller = Blueprint('spotify_blueprint', __name__)

spotifyService = ServiceFactory.get_spotify_service()

@controller.route('/auth')
def auth():
    return redirect(spotifyService.build_auth_request_url())

@controller.route('/callback')
def callback():
    auth_token = request.args['code']
    auth_header = spotifyService.authorize(auth_token)

    session['auth_header'] = auth_header

    return redirect('/profile')

@controller.route('/profile')
def user_profile():
    user_data = None
    listening_habits = None

    if 'auth_header' in session:
        user_data = spotifyService.get_user_profile(session['auth_header'])
        listening_habits = spotifyService.get_user_habits(session['auth_header'])

    return render_template('profile_template.html', user=user_data, habits=listening_habits)
    

src/templates/fragments/header_fragment.html
<nav>
    <div class="nav-wrapper">
        <a href="{{ url_for('home_blueprint.show_index') }}" class="brand-logo center">Spotlistify</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="{{ url_for('home_blueprint.show_index') }}">Home</a></li>
            <li><a href="#">Playlists</a></li>
        </ul>
        <ul class="right hide-on-med-and-down">
            <form>
                <div class="input-field">
                    <input id="search" placeholder="Search..." type="search" required>
                    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                    <i class="material-icons">close</i>
                </div>
            </form>
        </ul>
    </div>
</nav>

src/templates/fragments/meta_fragment.html
<head>
    <title>Spotlistify</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rock+Salt&display=swap" rel="stylesheet">    
    
    <link rel="stylesheet" href="{{ url_for('static', filename='third-party/materialize/css/materialize.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='third-party/materialize/js/materialize.min.js') }}"></script>
</head>

src/templates/fragments/signed_on_fragment.html
<div class="row">
    <div class="col l3 m12 s12">
        <img class="responsive-img" src="{{ user.images[0].url }}" title="{{ user.id }}'s profile picture" alt="{{ user.id }}'s profile picture" />
    </div>
    <div class="col l9 m12 s12">
        <h6 class="hide-on-med-and-down"><strong>Your Spotify Account:</strong></h6>

        <table class="highlight">
            <tr>
                <th>User:</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Account Type:</th>
                <td>{{ user.type }}</td>
            </tr>
            <tr>
                <th>User Country:</th>
                <td>{{ user.country }}</td>
            </tr>
            <tr>
                <th>Profile Page:</th>
                <td><a href="{{ user.external_urls.spotify }}">{{ user.id }}'s Spotify Profile</a></td>
            </tr>
        </table>
    </div>
</div>
<div class="row">
    {% if habits and habits.items[0] %}
        
    {% else %}
        <p>You have no recent listening habits</p>    
    {% endif %}
</div>

src/templates/home_template.html
{% extends 'main_layout_template.html' %}

{% block content %}
    <div class="card">
        <div class="card-content">
            <a href="{{ url_for('spotify_blueprint.auth') }}">Authenticate Spotify</a>
        </div>
    </div>
{% endblock content %}

src/templates/main_layout_template.html
<html>
    {% include 'fragments/meta_fragment.html' %}

    <body>
        {% include 'fragments/header_fragment.html' %}

        <div class="container top-div">
            {% block content %}{% endblock content %} 
        </div>
    </body>
</html>

src/templates/profile_template.html
{% extends 'main_layout_template.html' %}

{% block content %}
    <div class="card">
        <div class="card-content">
            {% if user %}
                {% include 'fragments/signed_on_fragment.html' %}
            {% else %} 
                <p>You must authorize Spotify in order to use this application.</p>

                <a href="{{ url_for('spotify_blueprint.auth') }}">Login to Spotify</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}